#!/bin/bash

usage="Usage: $(basename "$0") <category> <id>"

if [ "$#" -ne 2 ] || [ -z "$1" ] || [ -z "$2" ]; then echo "$usage"; exit 1; fi

entry=$(pactl -f json list "$1" |
    jq --argjson id "$2" '.[] | select(.index == $id)')

if [ -z "$entry" ]; then echo "Could not find '$1' with id '$2'"; exit 1; fi

if [ "$(echo "$entry" | jq '.mute')" = 'true' ]; then echo 'muted'; exit 0; fi

echo "$entry" | jq -r '.volume | to_entries | .[0].value.value_percent'