#!/bin/bash
pacmd list-sink-inputs |
    grep -E "index: |$1" |
    xargs echo | # converts the input into a space-separated string and outputs it
    grep -Po '(index: \d+\s(?!index: ))' |
    grep -Po '\d+'