#!/bin/bash
# usage: cat input.txt | xargs SpotifyTracksToYtPlaylist

cache="$HOME/.cache/SpotifyTracksToYtPlaylist.cache"
mkdir -p "$(dirname "$cache")"
touch "$cache"

for spotifyId in $@; do
    ytId=$(grep "^$spotifyId:" "$cache" |
        cut -d ":" -f 2)

    if [ -z "$ytId" ]; then
        ytId=$(SpotifyTrackGetArtistAndTitle $spotifyId |
            xargs -0 YtGetFirstId)
        echo $spotifyId:$ytId >> $cache
    fi

    ytIds+=($ytId)
done

random=false
if $random; then
    ytIds=($(shuf -e "${ytIds[@]}"))
fi

echo $(YtGeneratePlaylist "${ytIds[@]}")