#!/bin/bash
usage="Example: cat input.txt | xargs SpotifyToYt"

for arg in "$@"; do case "$arg" in
    '-h' | '--help')
        echo "$usage"; exit 0 ;;
    '-r')
        random=true ;;
    *)
        spotifyIds+=("$arg") ;;
esac done

if [ -z "${spotifyIds[*]}" ]; then
    echo "$usage"; exit 0
fi

cache="$HOME/.cache/SpotifyToYt.cache"
mkdir -p "$(dirname "$cache")"
touch "$cache"

for spotifyId in "${spotifyIds[@]}"; do
    ytId=$(grep "^$spotifyId:" "$cache" |
        cut -d ":" -f 2)

    if [ -z "$ytId" ]; then
        ytId=$(SpotifyTrackGetArtistAndTitle "$spotifyId" |
            xargs -0 YtGetFirstId)

        if [ -z "$ytId" ]; then 
            echo "nothing found for spotify id '$spotifyId'"
            exit 1
        fi

        echo "$spotifyId:$ytId" >> "$cache"
    fi

    ytIds+=("$ytId")
done

if [ "$random" = true ]; then
    mapfile -t ytIds < <(shuf -e -- "${ytIds[@]}")
fi

YtGeneratePlaylist "${ytIds[@]}"