#!/bin/bash
# usage: cat input.txt | xargs SpotifyTracksToYtPlaylist

for arg in "$@"; do case "$arg" in
    '-r')
        random=true ;;
    *)
        spotifyIds+=("$arg") ;;
esac done

cache="$HOME/.cache/SpotifyTracksToYtPlaylist.cache"
mkdir -p "$(dirname "$cache")"
touch "$cache"

for spotifyId in "${spotifyIds[@]}"; do
    ytId=$(grep "^$spotifyId:" "$cache" |
        cut -d ":" -f 2)

    if [ -z "$ytId" ]; then
        ytId=$(SpotifyTrackGetArtistAndTitle "$spotifyId" |
            xargs -0 YtGetFirstId)
        echo "$spotifyId:$ytId" >> "$cache"
    fi

    ytIds+=("$ytId")
done

if [ "$random" = true ]; then
    ytIds=($(shuf -e "${ytIds[@]}"))
fi

echo $(YtGeneratePlaylist "${ytIds[@]}")